<a href="https://colab.research.google.com/github/farahnda/Learning/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import tensorflow as tf

In [22]:
mnist = tf.keras.datasets.mnist # AMBIL OBJEK DATASET MNIST YG DISEDIAKAN TENSORFLOW
(x_train, y_train), (x_test, y_test) = mnist.load_data() # buat dataset (bagi 2 dtraining & dtesting)
x_train, x_test = x_train / 255.0, x_test / 255.0 # normalisasi gambar pixel (0-255 nilainya)
# neural network lebih mudah b elajar jika semua fitur berada di skala sama

In [23]:
# BUAT MODEL (SEQUENTIAL = DATA NGALIR DARI ATAS KE BAWAH)
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                    # ubah jadi 28 x 28 = 784 angka
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    # 784 -> 128, tiap neuron trima semua input (Fully Connected Layer)
                                    # ReLU = fungsi -> f(x)=max(0,x)
                                    tf.keras.layers.Dropout(0.2),
                                    # neuron matikan acak ketika training (20% nya) biar ga depending & kurangi overfitting
                                    tf.keras.layers.Dense(10)])
                                    # 10 kelas jadi skor mentah (logits), belum berupa probabilitas

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [24]:
predictions = model(x_train[:1]).numpy() # predik 1 gambar pertama trus masukkin ke model
predictions

array([[-0.00587396, -0.1771624 ,  0.38169467,  0.64750046, -0.11157411,
        -0.06388924,  0.05221017, -0.11385038,  1.0845746 ,  0.04167984]],
      dtype=float32)

In [25]:
tf.nn.softmax(predictions).numpy() # softmax ubah logits jadi probabilitas

array([[0.07655162, 0.06450075, 0.1127907 , 0.1471334 , 0.06887306,
        0.07223682, 0.08112973, 0.06871647, 0.22778764, 0.08027988]],
      dtype=float32)

In [26]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
# HITUNG LOSS (seberapa jauh prediksi model dari jawaban benar)
loss_fn(y_train[:1], predictions).numpy() #  LOSS NYA GEDE, 0 hampir sempurna; >2 sgt buruk

np.float32(2.6278052)

In [27]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
# compile/konfig proses training
# optimizer pake Adam buat perbarui bobot model agar loss turun
# Loss pake SparseCategoricalCrossentropy sebagai fungsi yang dioptimalkan
# Metrics tampilkan accuracy biar tau prediksi benar
model.fit(x_train, y_train, epochs=5) # epoch: satu siklus penuh di mana seluruh dataset pelatihan (data latih) diproses oleh model.
# prediksi dgn 5 siklus

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9135 - loss: 0.2945
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.9573 - loss: 0.1428
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9670 - loss: 0.1068
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9725 - loss: 0.0883
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9771 - loss: 0.0723


In [29]:
model.evaluate(x_test, y_test, verbose=2)
# evaluasi dengan verbose=2 -> tampilin ringkasan metrik(loss/akurasi dalam bentuk 1 baris teks baru tiap kali 1 epoch selesai, tanpa bilah anomasi)

313/313 - 1s - 4ms/step - accuracy: 0.9743 - loss: 0.0817


[0.08166442811489105, 0.9743000268936157]

In [30]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
# MODEL SEBELUMNYA HASILKAN LOGITS (SKOR MENTAH),
# DGN TMBAHIN SOFTMAX -> BUAT MODEL BARU YG LANGSUNG UBAH LOGITS JADI PROBABILITAS
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.68117924e-06, 3.78794907e-09, 3.43431566e-07, 1.76866655e-04,
        1.56391393e-11, 8.75082122e-08, 3.96659295e-14, 9.99817193e-01,
        2.45859979e-07, 2.59576291e-06],
       [8.55366000e-09, 1.81808537e-05, 9.99980450e-01, 1.03736852e-06,
        3.48172406e-15, 2.01180725e-07, 1.32373131e-07, 1.24076105e-14,
        1.11755822e-08, 2.25060307e-16],
       [1.55825785e-06, 9.97293651e-01, 4.43590863e-04, 3.60981940e-05,
        1.42420604e-05, 2.60507659e-05, 7.36067068e-06, 9.73422779e-04,
        1.19246182e-03, 1.16745132e-05],
       [9.99932766e-01, 1.76906975e-10, 4.75751585e-05, 1.14300747e-07,
        5.09925435e-08, 8.57794532e-07, 1.34207512e-05, 6.69569147e-07,
        1.75562249e-08, 4.53202892e-06],
       [1.10859946e-05, 3.86526331e-08, 3.99421187e-05, 1.50199767e-07,
        9.97902393e-01, 5.57017984e-06, 1.86054560e-04, 9.92902824e-06,
        9.48808406e-07, 1.84382510e-03]], dtype=float32)>